### ISSUE TITLE
[Bolt/Wallet-tts] Testo pagina primo accesso

### ISSUE THREAD

**Issue by FeliceBalsamo** [napoliblockchain/napay-docs#76]
Ciao,

a breve attiverai il tuo nuovo portafoglio TTS, potrai così ricevere ed inviare token (buoni sconti) tra le attività aderenti al progetto. 

Il tuo portafoglio elettronico (wallet), sarà reso sicuro grazie ad un processo matematico che renderà illeggibile il contenuto. Per fare ciò verranno scelte a caso dal tuo smartphone o dal tuo pc alcune parole (seed) in lingua inglese, le quali grazie ad un processo crittografico renderanno inaccessibile il tuo portafoglio.
Queste parole casuali saranno uniche al mondo e ti consentiranno di recuperare il contenuto del tuo portafoglio anche in caso di perdita del tuo dispositivo. Ma attenzione, conservale in un luogo sicuro perché chiunque entri in possesso di questa chiave può accedere al suo contenuto.

Ogni tanto ricorda di fare un backup del tuo portafoglio digitale è un passaggio importante per proteggere il tuo patrimonio.

Se possiedi invece stai ripristinando il tuo portafoglio e hai una chiave mnemonica (seed) premi sul pulsante "Ripristina".

Se invece vuoi generare un nuovo portafoglio digitale clicca sul pulsante "Nuovo" e segui le istruzioni raccomandate.

Se vuoi uscire, clicca sul pulsante "Esci"

**Comment by jambtc** [comment]
Verranno scelte 12 parole che identificano in maniera univoca il tuo portafoglio.

**Comment by jambtc** [comment]
Hi, 
soon you will activate your new TTS wallet, so you will be able to receive and send tokens (discount coupons) among the activities participating in the project.
Your electronic wallet will be made secure thanks to a mathematical process that will make the content unreadable. So, 12 words will be chosen that uniquely identify your wallet. The merit is of cryptography, in particular of the hierarchical deterministic portfolio concept, which, thanks to the use of some mathematical functions, allows users, starting from the seed, to recover everything.
These random words will be unique in the world and will allow you to recover the contents of your wallet even in case of loss of your device. But be careful, keep them in a safe place so that anyone who gets hold of this key can access its contents.
Remember to make a backup of your digital wallet. This is an important step in securing your asset.

If you already have a mnemonic key (seed) and want to restore your old wallet, press the button <i><b>"Restore"</b></i>

If you want to generate a new digital wallet, click on the <i><b>"New"</b> </i> button and follow the recommended instructions.

If you want to exit, click on the <i><b>"Logout"</b> </i> button.

**Comment by jambtc** [comment]
chiuso
